FROM centos:centos7.3.1611

LABEL maintainer="Hiro Maru <hiro.maruhashi@nysol.co.jp>"

# 基本ライブラリ
RUN yum -y update; \
    yum -y groupinstall "Development Tools"; \
    yum -y install boost-devel libxml2-devel \
                   quota \
                   nano; \
    rm -rf /var/cache/yum/*; yum clean all;

# 言語を日本語に設定（必ずyum updateやyum reinstall glibcの後に実行)
RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"
# 日付を日本語に設定
RUN echo 'ZONE="Asia/Tokyo"' > /etc/sysconfig/clock; \ 
    rm -f /etc/localtime; \
    ln -fs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime;

# Work Directories
WORKDIR /work
WORKDIR /github

# ruby
WORKDIR /github
RUN git clone https://github.com/sstephenson/rbenv.git
RUN echo 'export RBENV_ROOT="/github/rbenv"' >> ~/.bash_profile;\
    echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> ~/.bash_profile;\
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile;
ENV RBENV_ROOT /github/rbenv
ENV PATH /github/rbenv/bin:$PATH
RUN rbenv init -
RUN git clone git://github.com/sstephenson/ruby-build.git
WORKDIR ruby-build
RUN ./install.sh; \
    yum install -y zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel; \
    rm -rf /var/cache/yum/*; yum clean all; \
    rbenv install 2.5.1; rbenv rehash; rbenv global 2.5.1;

# python
WORKDIR /github
RUN git clone https://github.com/pyenv/pyenv.git
RUN echo 'export PYENV_ROOT="/github/pyenv"' >> ~/.bash_profile;\
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile;\
    echo 'eval "$(pyenv init -)"' >> ~/.bash_profile;
ENV PYENV_ROOT /github/pyenv
ENV PATH /github/pyenv/bin:$PATH
RUN pyenv init -
RUN pyenv install 3.6.5; pyenv global 3.6.5;

# rbenv/pyenv関連パス設定
ENV PATH $RBENV_ROOT/shims:$RBENV_ROOT/plugins/ruby-build/bin:$PATH
ENV PATH $PYENV_ROOT/shims:$PATH

# mcmd
WORKDIR /github
RUN git clone https://github.com/nysol/mcmd.git; \
    cd mcmd; aclocal; autoreconf -i; ./configure; make; make install; \
    rm -rf /github/mcmd;

# nysol_python
RUN echo '2019/06/01 0:00'
WORKDIR /github
RUN git clone https://github.com/nysol/nysol_python.git
WORKDIR nysol_python
RUN python setup.py build;
RUN python setup.py install;

# mbomsai, mkmeans, etc
WORKDIR /github
RUN git clone https://github.com/nysol/mcmdex.git; \
    cd mcmdex; aclocal; autoreconf -i; ./configure; make; make install; \
    rm -rf /github/mcmdex.git;

# nysol_ruby
# RUN gem install nysol-ruby
