FROM centos:centos8.2.2004

LABEL maintainer="Hiro Maru <hiro.maruhashi@nysol.co.jp>"

# 基本ライブラリ
RUN yum -y update; \
    yum -y groupinstall "Development Tools"; \
    yum -y install boost-devel libxml2-devel \
                   glibc-locale-source glibc-langpack-en \
                   quota \
                   libcurl-devel \
                   nano; \
    yum -y install epel-release; \
    yum -y install https://www.elrepo.org/elrepo-release-8.0-2.el8.elrepo.noarch.rpm; \
    yum -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm; \
    sed -i -e s/enabled=0/enabled=1/g /etc/yum.repos.d/CentOS-PowerTools.repo; \
    rm -rf /var/cache/yum/*; yum clean all;

# 言語を日本語に設定（必ずyum updateやyum reinstall glibcの後に実行)
RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"
# 日付を日本語に設定
RUN echo 'ZONE="Asia/Tokyo"' > /etc/sysconfig/clock; \
    rm -f /etc/localtime; \
    ln -fs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime;

# Work Directories
WORKDIR /work
WORKDIR /github

# ruby
RUN cd /github; git clone https://github.com/rbenv/rbenv.git;\
    echo 'export RBENV_ROOT="/github/rbenv"' >> ~/.bash_profile;\
    echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> ~/.bash_profile;\
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile;
ENV RBENV_ROOT="/github/rbenv" \
    PATH="/github/rbenv/bin:$PATH"
RUN rbenv init -;\
    cd /github; git clone https://github.com/rbenv/ruby-build.git;\
    cd ruby-build;\
    ./install.sh; \
    yum install -y zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel; \
    rm -rf /var/cache/yum/*; yum clean all; \
    rbenv install 2.7.2; rbenv rehash; rbenv global 2.7.2;

# python
RUN cd /github; git clone https://github.com/pyenv/pyenv.git;\
    echo 'export PYENV_ROOT="/github/pyenv"' >> ~/.bash_profile;\
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile;\
    echo 'eval "$(pyenv init -)"' >> ~/.bash_profile;
ENV PYENV_ROOT="/github/pyenv" \
    PATH="/github/pyenv/bin:$PATH"
RUN yum install -y libffi-devel;\
    rm -rf /var/cache/yum/*; yum clean all;\
    pyenv init -; pyenv install 3.9.0; pyenv global 3.9.0;
RUN pip install --upgrade pip;\
    pip install pip-review;

# rbenv/pyenv関連パス設定
ENV PATH="$PYENV_ROOT/shims:$RBENV_ROOT/shims:$RBENV_ROOT/plugins/ruby-build/bin:$PATH"

# node.js
RUN yum -y install nodejs;\
    rm -rf /var/cache/yum/*; yum clean all;\
    \
    npm update npm;\
    npm install -g n;\
    n latest;

# mcmd, mdmdex ( mbomsai, mkmeans, etc )
RUN cd /github; git clone https://github.com/nysol/mcmd.git;\
    cd mcmd; aclocal; autoreconf -i; ./configure; make; make install;\
    rm -rf /github/mcmd;\
    \
    cd /github; git clone https://github.com/nysol/mcmdex.git;\
    cd mcmdex; aclocal; autoreconf -i; ./configure; make; make install;\
    rm -rf /github/mcmdex.git;

###<<< step-b1
