FROM nysol/core:step-a.0.1.3

LABEL maintainer="Hiro Maru <hiro.maruhashi@nysol.co.jp>"

# zdd
RUN gem install nysol-zdd

# take
RUN gem install nysol-take

# mining
RUN gem install nysol-mining
#  - gpmetis
RUN rpm -Uvh http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/m/metis-5.1.0-12.el7.x86_64.rpm

# mruby, meach, etc
RUN gem install nysol

# view
RUN gem install nysol-view

# fumi
RUN gem install nysol-fumi
#  - JUMAN
WORKDIR /work
RUN curl -O http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/juman/juman-7.01.tar.bz2; tar jxvf juman-7.01.tar.bz2;\
    cd juman-7.01; ./configure; make; make install; rm -rf /work/*;
#  - KNP
WORKDIR /work
RUN curl -O http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/knp/knp-4.19.tar.bz2; tar jxvf knp-4.19.tar.bz2;\
    cd knp-4.19; ./configure; make; make install; rm -rf /work/*;
#  - ENJU
WORKDIR /github
RUN git clone https://github.com/mynlp/enju.git; \
    cd enju; ./configure; make; make install; \
    rm -rf /github/enju;

### その他ライブラリ
# nkf
RUN yum -y install epel-release nkf; \
    rm -rf /var/cache/yum/*; yum clean all;
# graphviz
RUN yum -y install 'graphviz': \
    rm -rf /var/cache/yum/*; yum clean all;
# R
RUN yum -y install R; \
    rm -rf /var/cache/yum/*; yum clean all;
# 日本語フォント for matplotlib
ADD IPAfont00303.zip /usr/share/fonts
RUN unzip -d /usr/share/fonts /usr/share/fonts/IPAfont00303.zip

# nysol_python
RUN echo '2019/06/01 0:00'
WORKDIR /github
RUN git clone https://github.com/nysol/nysol_python.git
WORKDIR nysol_python
RUN python setup.py build;
RUN python setup.py install;

# mbomsai, mkmeans, etc
WORKDIR /github
RUN git clone https://github.com/nysol/mcmdex.git; \
    cd mcmdex; aclocal; autoreconf -i; ./configure; make; make install; \
    rm -rf /github/mcmdex.git;

# nysol_ruby
# RUN gem install nysol-ruby
