FROM nysol/core:step-b.0.1.3

LABEL maintainer="Hiro Maru <hiro.maruhashi@nysol.co.jp>"

### application用
# python
RUN pip install --upgrade pip
RUN pip install flask
RUN pip install -U flask-cors
# ruby
RUN gem install thin
RUN gem install sinatra
RUN gem install sinatra-contrib
# node.js
RUN yum -y install nodejs; rm -rf /var/cache/yum/*; yum clean all;
# websocket for python
RUN pip install gevent-websocket

### 追加Rライブラリ
RUN R -e "install.packages('igraph', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('glmnet', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('ROCR', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('tgp', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('arulesSequences', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('LPCM', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('LICORS', repos='http://cran.rstudio.com/')"
### 追加pythonライブラリ
RUN pip install jupyterhub
RUN npm install -g configurable-http-proxy
RUN pip install notebook
RUN pip install numpy
RUN pip install pandas -U
RUN pip install matplotlib bokeh plotly
RUN pip install scipy
RUN pip install scikit-learn
RUN pip install pip-review
RUN pip install python-Levenshtein
RUN pip install python-igraph
RUN pip install param
RUN pip install 'holoviews[recommended]'
RUN rpm -Uvh http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm
RUN yum -y install mysql-community-client; rm -rf /var/cache/yum/*; yum clean all;
RUN pip install pymysql
RUN pip install ipython-sql
RUN pip install pyper
RUN pip install opencv-python
RUN pip install scikit-image
RUN pip install mglearn
RUN pip install pydot
RUN pip install keract
RUN pip install pydotplus

# ユーザー環境設定
WORKDIR /work
ENV LD_LIBRARY_PATH /usr/local/lib
